modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cobblefurnies"
version = "${version}"
displayName = "CobbleFurnies"
authors = "LunazStudios"
description = '''
Whether you're building a professor's lab, a bustling Pok√©center, or just a cozy cabin in the woods, CobbleFurnies is here to make your world feel more alive!
'''
logoFile = "icon.png"

[[dependencies.cobblefurnies]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblefurnies]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblefurnies]]
modId = "cobblemon"
type = "required"
versionRange = "[1.7.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblefurnies]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "cobblefurnies.mixins.json"
